controller_list:
  - name: fake_irb_120_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_robotiq_85_controller
    joints:
      - gripper_finger1_joint