# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: irb_120
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    - gripper_finger1_joint
  sim_control_mode: 1  # 0: position, 1: velocity

# List here the two command controllers: one for the arm and other for the gripper
controller_list:
  - name: ""
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]
  - name: "gripper_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints: [gripper_finger1_joint]

